### ISSUE TITLE
Clean up example and put it above

### ISSUE THREAD

**Issue by ai** [storeon/undo#1]
1. `const { dispatch } = useStoreon('undoable')`  you do not need for `'undoable'`
2. You can show a simple example with GIF without counter boilerplate just after the first description
3. `<React.Fragment>`  → `<>`
4. Remove new line before `</React.Fragment>`

**Comment by ai** [comment]
Also we can clean `counter2` from full example

**Comment by polemius** [comment]
I've cleaned up the readme. But I'm not sure what did you mean in `1`? That no need put `undoable` word in `useStoreon` function?

**Comment by ai** [comment]
`const { dispatch } = useStoreon('undoable')` > `const { dispatch } = useStoreon()`

**Comment by ai** [comment]
You need show also basic example in first section, maybe before the GIF.

**Comment by polemius** [comment]
I've added the basic example in the first section

**Comment by ai** [comment]
Let’s keep it open until you update example according https://github.com/polemius/undo/issues/3

**Comment by polemius** [comment]
@ai Looks like all points from this first messages is covered. Could I close this issue? Or do you want add something else?

**Comment by ai** [comment]
Yeap, it looks good now
