### ISSUE TITLE
Add API to have separated history for different state keys

### ISSUE THREAD

**Issue by ai** [storeon/undo#3]
In `storeon/router` discussion we found that having one global history on any store changes can not be so useful?

In most of cases user will need to undo only some specific events? For instance, it could be undo for text editor (and should not care about menu state) or it could be nice to have undo for URL changes.

It also could be interesting to have 2 separated histories.

```js
let history = createHistory(['key'])
createStore([history.module])
dispatch(history.undo)
```

**Comment by polemius** [comment]
I've prepare the [PR](#5) with functionality for separete history. Can you please check it?

**Comment by ai** [comment]
Looks great

**Comment by polemius** [comment]
Thanks :) 
Can I now more this repo to @storeon? Or you think that I should add something more?

**Comment by ai** [comment]
> Can I now more this repo to @storeon?

Of course. And you can release it under `@storeon` npm org. Just ping me when you will rename the project and release a new version.

**Comment by polemius** [comment]
The 0.1.0 version of @storeon/undo is here. So, I'm going to close this issue.
