### ISSUE TITLE
Move project to storeon org

### ISSUE THREAD

**Issue by ai** [storeon/undo#6]
Do not forget to send PR to https://github.com/storeon/storeon#tools

**Comment by polemius** [comment]
I've published undo package but with `npm publish`. Because `yarn clean-publish` shows me the error:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ex0/.npm/_logs/2019-05-15T19_58_21_483Z-debug.log
Done in 1.67s.
```

**Comment by ai** [comment]
Can you enable 2FA for login at npm?

**Comment by polemius** [comment]
I've disabled it to login from cli. Now I enable it again.

**Comment by polemius** [comment]
The `undo` module now under the storeon organization. So, I'm going to close this issue.
